"""Unified session-inspection contracts for OrbitOps."""

from .correlation import (
    CONTRACT_SEMANTICS,
    LANE_PRECEDENCE,
    PAIR_CORRELATION_RULES,
    ContractSemantics,
    CorrelationBasis,
    CorrelationDecision,
    CorrelationKind,
    CorrelationRule,
    EvidenceLane,
    SourceCompleteness,
    classify_source_completeness,
    classify_telemetry_alarm_match,
    correlation_rule,
    presentation_key,
)
from .errors import (
    IncompatibleEvidenceError,
    IncompleteEvidenceError,
    MalformedEvidenceError,
    SessionInspectionError,
)
from .inspection import inspect_session
from .models import (
    Diagnostic,
    DiagnosticCode,
    DiagnosticSeverity,
    LaneSummary,
    NormalizedSession,
    SourceDescriptor,
    TimelineEntry,
    TimelineEntryKind,
)

__all__ = [
    "CONTRACT_SEMANTICS",
    "LANE_PRECEDENCE",
    "PAIR_CORRELATION_RULES",
    "ContractSemantics",
    "CorrelationBasis",
    "CorrelationDecision",
    "CorrelationKind",
    "CorrelationRule",
    "Diagnostic",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "EvidenceLane",
    "IncompatibleEvidenceError",
    "IncompleteEvidenceError",
    "LaneSummary",
    "MalformedEvidenceError",
    "NormalizedSession",
    "SessionInspectionError",
    "SourceCompleteness",
    "SourceDescriptor",
    "TimelineEntry",
    "TimelineEntryKind",
    "classify_source_completeness",
    "classify_telemetry_alarm_match",
    "correlation_rule",
    "inspect_session",
    "presentation_key",
]
